source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.coding.net/leqi/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'PodTest' do
    pod 'JGProgressHUD', '~> 1.4’
    pod 'SnapKit', '~> 3.0.2’
    pod 'Alamofire', ’~> 4.0’
    pod 'JPSVolumeButtonHandler', '~> 1.0.2'
    pod 'Safelight', '~> 2.0.5’
end
