platform :ios, '8.0'
use_frameworks!

target 'logDemo' do
    #日志相关
    pod 'CocoaLumberjack'
    pod 'LumberjackConsole'
    pod 'NBULog'
    #数据库
    pod 'JQFMDB'
    #JSON模型
    pod 'MJExtension'
    #网络
    pod 'AFNetworking', '~> 3.1.0'

end
