platform :ios, '8.0'
use_frameworks!

target 'WingsBurning' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.10'
    pod 'HappyDNS', '~> 0.3.10'
    pod 'MMDrawerController', '~> 0.6.0'
    pod 'Masonry', '~> 1.0.1'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'MJRefresh', '~> 3.1.9'
    pod 'M80AttributedLabel', '~> 1.3.3'
    pod 'JZLocationConverter', '~> 1.0.0'
    pod 'FSCalendar', '~> 2.6.0'
    pod 'UMengAnalytics-NO-IDFA', '~> 4.1.5'
    pod 'JPush', '~> 2.2.0'

end


