
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'mugshot' do
pod 'Alamofire', '~> 3.0'
pod 'SDWebImage', '~> 3.7'
pod 'JGProgressHUD', '~> 1.2'
pod 'DAAlertController', '~> 0.1.4'
pod 'UMengAnalytics-NO-IDFA', '~> 3.1.11'
pod 'SnapKit', '~> 0.18.0'
pod 'JPSVolumeButtonHandler','~> 1.0.0'
pod 'UMengSocialCOM', '~> 5.2.1'
end

target 'mugshotPro’ do
pod 'Alamofire', '~> 3.0'
pod 'SDWebImage', '~> 3.7'
pod 'JGProgressHUD', '~> 1.2'
pod 'DAAlertController', '~> 0.1.4'
pod 'UMengAnalytics-NO-IDFA', '~> 3.1.11'
pod 'SnapKit', '~> 0.18.0'
pod 'JPSVolumeButtonHandler','~> 1.0.0'
pod 'UMengSocialCOM', '~> 5.2.1'
end