platform :ios, '8.0'
use_frameworks!

target 'WingsBurning' do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJExtension', '~> 3.0.13'
    pod 'MMDrawerController', '~> 0.6.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'M80AttributedLabel', '~> 1.6.2'
    pod 'FSCalendar', '~> 2.7.3'
    pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
    pod 'JPush', '~> 3.0.2'
    pod 'Qiniu', '~> 7.1.5'
    pod 'OpenShare', '~> 0.0.1'
    pod 'AMapLocation-NO-IDFA', '~> 2.3.1'
end


