platform :ios, '8.0'
#xcodeproj 'ShiJia.xcodeproj'

#inhibit_all_warnings!                              # 忽略所有警告
use_frameworks!

def pods
    # Model
    pod 'AFNetworking'                                 # 网络请求框架
    pod 'AFXMLDictionarySerializer'                    # 将XML转换为NSDictionary in AFNetworking 2.0.
    pod 'AFNetworkActivityLogger'
    pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master' 
    #pod 'DeepLinkKit'                                  # 路由匹配框架，使用基于 block API 处理你的深链接
    pod 'ReactiveCocoa'                                # 一个将函数响应式编程范例带入Objective-C的开源库
    pod 'ReactiveViewModel'                            # RAC支持MVVM的辅助类
    pod 'CocoaAsyncSocket'                             # 异步 socket 网络库
    #pod 'FMDB'                                         # SQLite 的 Cocoa/Objective-C 封装
    
    # View
    pod 'REMenu'                                       # 实现类似Vine的下拉菜单
    pod 'MJRefresh'                                    # 上下拉刷新框架
    pod 'Masonry'                                      # 自动布局框架
    pod 'MBProgressHUD'  ,  '~> 0.9.2'                  # 用于显示一个半透明的 HUD
    pod 'YYKit'                                        # 多功能iOS 组件
    pod 'AsyncDisplayKit', '~> 1.9.90'                 # 使一个很复杂的用户界面保持平滑和反应灵敏的框架
    pod 'BarrageRenderer'                              # 弹幕开源库
    
    # Extra
    pod 'PinYin4Objc'                                  # 汉字转拼音类库，支持简体和繁体中文
    pod 'JSONModel'                                    # 基于 JSON 的数据模型化框架
    pod 'GTMBase64'                                    # Base64 from Google Toolbox
    
    # Log
    pod 'CocoaLumberjack'                              # 日志核心框架
    pod 'LumberjackConsole'                            # 日志显示框架
    pod 'NBULog'                                       # 日志Optional for dynamic log levels
    
    
    # Tool
    pod 'Bugtags'                                      # Bug管理框架
    pod 'WeiboSDK'
    pod 'FWeiXinSDK', '~> 0.0.3'
  # pod 'KMCGeigerCounter'                             # iOS帧速计算器
    pod 'Reveal-iOS-SDK', :configurations => ['Debug'] # 界面调试工具
    pod 'MJExtension'
    pod 'NSDate+Calendar'

    pod 'UPYUN', '~> 1.0.0'                             #又拍云
    pod 'Bugly'                                         #重视Crash, Crash上报
    pod 'SDWebImage', '~> 3.7.3'                        #图片异步 缓存

    pod 'UMengAnalytics'                                #标准SDK，含IDFA
  #  pod 'JxbDebugTool', '~> 4.4', :configurations => ['Debug']
end

target 'ShiJia_BeiJing' do
    pods
    
end

target 'ShiJia_JiangSu' do
    pods

end
